### PR TITLE
Spi2 working with FPGA

### PR DESCRIPTION
**Pull request by wajahat-abbas**
Notes:
- Pull requests will not be accepted until the submitter has agreed to the [contributer agreement](https://github.com/ARMmbed/mbed-os/blob/master/CONTRIBUTING.md).
- This is just a template, so feel free to use/remove the unnecessary things

## Description

A few sentences describing the overall goals of the pull request's commits.

## Status

**READY/IN DEVELOPMENT/HOLD**

## Migrations

If this PR changes any APIs or behaviors, give a short description of what *API users* should do when this PR is merged.

YES | NO

## Related PRs

List related PRs against other branches:

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Todos

- [ ] Tests
- [ ] Documentation

## Deploy notes

Notes regarding the deployment of this PR. These should note any required changes in the build environment, tools, compilers and so on.

## Steps to test or reproduce

Outline the steps to test or reproduce the PR here.

### CODE REVIEW

**Review by RobMeades — CHANGES_REQUESTED** [review]
Suggest that, rather than changing the SPI frequency in the `driver/SPI.cpp` file, change it in the `spi_init()` function with a call to `spi_frequency()` and put a comment against that along the lines of /* TODO: the low clock frequency is required for FPGA operation, will remove this line and return to 1 MHz operation on the real chip */.

**Review by RobMeades — CHANGES_REQUESTED** [review]
One more thing: I see that we're adding `SPI_SLAVE` to the device capabilities; have we tested `SPI_SLAVE`?

**Comment by wajahat-abbas** [comment]
Slave is not yet tested but the implementation was already present in Mudassir's driver as i pulled his PR and made changes. This PR is generated only for our reference because SPI1 is not yet working so changes are expected in this driver and gpio driver as well

**Comment by RobMeades** [comment]
That's fine, provided that everyone involved knows that `SPI_SLAVE` doesn't necessarily work yet despite it being present in `targets.json`.

**Comment by wajahat-abbas** [comment]
Once SPI1 is working, i will test the slave and make a final PR which is merge-able

**Pull request closed without merging**
